spring:
  datasource:
    url: jdbc:mysql://localhost:3306/adonis_security
    username: root
    password: engbanda.com
  jpa:
    properties:
      hibernate:
#        dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: create
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 90097889292-6uu80pgg5ttp1dem9dram85qr8tu5r74.apps.googleusercontent.com
            client-secret: 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
            scope:
              - openid
              - profile
              - email
            authorization-grant-type: authorization_code
            redirect-uri: http://localhost:8080
            client-name: Google
          github:
            client-id: Iv23liTxhKbSQ4Ctq1Za
            client-secret: 83660ee917b2444aa362ecf2cda6edec9b0a7b9b
            scope:
              - user:email
            authorization-grant-type: authorization_code
#            redirect-uri: http://localhost:8080
            client-name: GitHub
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            jwk-set-uri: https://www.googleapis.com/oauth2/v3/certs
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            jwk-set-uri: https://api.github.com/meta

